name: Github Workflow Permission Manager
run-name: Updating WorkFlow permission as per org-repos/repolist.txt and org-repos/thirdparty_sources.txt
on:
  workflow_dispatch:
env:
  org: BentlyNevada-bh
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: WorkFlow Permission Adding
        env:
          SUPER_SECRET: ${{ secrets.ORG_GH_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions \
            -d '{"enabled_repositories":"selected","allowed_actions":"selected"}'
            
            permissions=$(cat org-repos/thirdparty-sources.txt)
            content=$(echo "${permissions//$'\n'/}")
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions/selected-actions \ 
            -d '{"github_owned_allowed":true,"verified_allowed":true,"patterns_allowed":['"$content"']}'

            curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  https://api.github.com/orgs/${{ env.org }}/repos | jq '.[] | "\(.name) \(.id)"'
            for p in $(cat org-repos/repoids.txt); do
            curl -s -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/${{ env.org }}/actions/permissions/repositories/"$repo_id"
            done
        shell: bash
