name: Github Workflow One-Time
run-name: Workflow Onetime
on:
  workflow_dispatch:
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: WorkFlow Permission Adding
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
            echo ORG is " ${{ env.org }} "
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions \
            -d '{"enabled_repositories":"selected","allowed_actions":"selected"}'
            
            permissions=$(cat org-repos/thirdparty-sources.txt)
            content=$(echo "${permissions//$'\n'/}")
            echo "$content"
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions/selected-actions \ 
            -d '{"github_owned_allowed":true,"verified_allowed":true,"patterns_allowed":['"$content"']}'
            id=$(cat repoids.txt | tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo IDs are "$id"
            curl -s -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ env.org }}/actions/permissions/repositories -d '{"selected_repository_ids":['"$id"']}'
            
        shell: bash
