name: Github Permission Manager
run-name: GitHUB pErm
on:
  workflow_dispatch:
    inputs:
      repo_list:
        required: true
        type: string
        description: Repo list, if more than one, specify as comma seperated values
        default: "-"
jobs:
  org_permission:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Permission Changing
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
	  status_check=$(curl -L   -H "Accept: application/vnd.github+json"   -H "Authotion: Bearer $SUPER_SECRET"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/bhsankbab/actions/permissions | jq -r '.enabled_repositories')



