name: Github Permission Manager
run-name: GitHUB pErm
on:
  workflow_dispatch:
    inputs:
      repo_list:
        required: true
        type: string
        description: Repo list, if more than one, specify as comma seperated values
        default: "-"
jobs:
  org_permission:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:

      - name: Permission Changing
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
          declare -a repo_list=(${{ inputs.repo_list }})
          length=${#repo_list[@]}
          idx=0
          idr=()
          IFS=',' read -r -a repo <<< "${{ inputs.repo_list }}"
          for p in "${repo[@]}"; do
             echo "executing $p"
             repo_id=$(curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/bhsankbab/repos | jq '.[] | select(.name=="'$p'") | .id')
             idr[idx]="$repo_id" #store data in array
             idx=$((idx+1)) #increment the counter
          done         
          printf -v joined '%s,' "${idr[@]}"
          echo "${joined%,}"

