name: Github Permission Manager
run-name: GitHUB pErm
on:
  workflow_dispatch:
    inputs:
      repo_list:
        required: true
        type: string
        description: Repo list, if more than one, specify as comma seperated values
        default: "-"
jobs:
  org_permission:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Permission Changing
        run: |
          IFS=',' read -r -a repo <<< "${{ inputs.repo_list }}"
          for p in "${repo[@]}"; do
          echo "executing $p"
          status_check=$(curl -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/bhsankbab/actions/permissions | jq '.enabled_repositories')
          echo "$status_check"   
             if [ "$status_check" == "selected" ]; then
               repo_id=$(curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  https://api.github.com/orgs/bhsankbab/repos | jq '.[] | select(.name=="'$p'") | .id')
               curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  https://api.github.com/orgs/bhsankbab/actions/permissions/repositories -d '{"selected_repository_ids":['$repo_id']}'
             else
               echo " ORG settings for Action Permission is not Seletected for Repositories. Please change it and run the workflow"
             fi
          
          done
