name: Github Permission Manager
run-name: GitHUB pErm
on:
  workflow_dispatch:
    inputs:
      repo_list:
        required: true
        type: string
        description: Repo list, if more than one, specify as comma seperated values
        default: "-"
      operation:
        required: true
        type: choice
        description: ADD, DELETE Workflow Permissions
        options:
        - 'ADD'
        - 'DELETE'
jobs:
  org_permission:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Permission Adding
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
          status_check=$(curl -s -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/bhsankbab/actions/permissions | jq -r '.enabled_repositories')
          echo "$status_check"   
          if [ "$status_check" == "selected" ]; then
            IFS=',' read -r -a repo <<< "${{ inputs.repo_list }}"
            for p in "${repo[@]}"; do
            echo "executing $p"
            repo_id=$(curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  https://api.github.com/orgs/bhsankbab/repos | jq '.[] | select(.name=="'$p'") | .id')
            echo $repo_id
            curl -L -X ${{ inputs.operation }}  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/bhsankbab/actions/permissions/repositories/"$repo_id"
            done
          else
            echo " ORG settings for Action Permission is not Seletected for Repositories. Please change it and run the workflow"
          fi
        shell: bash 
