name: Github Secret Permission Adding 
run-name: Github Secret Permission Adding ${{ inputs.secret }} for the list in org-repos/repolist.txt
on:
  workflow_dispatch:
    inputs:
      repos:
        required: true
        type: string
        description: Specify Repo Names to be added. If more than one, use comma separated values
        default: "-"

env:
  org: bhsankbab
jobs:
  secret-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: Adding Secret Permission for Repo
        run: |
          status_check=$(curl -s -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/orgs/${{ env.org }}/actions/secrets/MY_TOKEN" | jq -r '.visibility')
          echo "$status_check"   
          if [ "$status_check" == "selected" ]; then
            IFS=',' read -r -a repo <<< "${{ inputs.repos }}"
            for p in "${repo[@]}"; do
            repo_id=$(curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  "https://api.github.com/orgs/${{ env.org }}/repos" | jq '.[] | select(.name=="'$p'") | .id')
            curl -s -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ORG_GH_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/orgs/${{ env.org }}/actions/secrets/GH_TOKEN/repositories/$repo_id"
            done
          else
            echo " ORG settings for Action Permission is not Seletected for Repositories. Please change it to selected and run the workflow"
          fi
        shell: bash
