name: Github Secret Permission Adding 
run-name: Github Secret Permission Adding ${{ inputs.secret }} for the list in org-repos/repolist.txt
on:
  workflow_dispatch:
    inputs:
      repos:
        required: true
        type: string
        description: Specify Repo Names to be added. If more than one, use comma separated values
        default: "-"

env:
  org: bhsankbab
jobs:
  secret-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: Adding Secret Permission for Repo
        run: |
          curl  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/orgs/${{ env.org }}/actions/secrets/MY_TOKEN" | jq
          status_check=$(curl -s -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/orgs/${{ env.org }}/actions/secrets/MY_TOKEN" | jq -r '.visibility')
          echo  Status is "$status_check"   
          if [ "$status_check" == "selected" ]; then
            IFS=',' read -r -a repo <<< "${{ inputs.repos }}"
            for p in "${repo[@]}"; do
            curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  "https://api.github.com/orgs/${{ env.org }}/repos" | jq '.[] | select(.name=="'$p'") | .id' >> org-repos/secrets_ids.txt
            done
            IDS=$(cat org-repos/secrets_ids.txt | tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo " $IDS "
            curl -s -L -X PUT   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  "https://api.github.com/orgs/bhsankbab/actions/secrets/MY_TOKEN/repositories" -d '{"selected_repository_ids":['"$IDS"']}'
            COMMIT_MESG=$(git log -1 --pretty=format:%s | head -n 1)
            GIT_RETRY=0
            until [ "$GIT_RETRY" -ge 10 ]
            do
            git add org-repos
            git diff --quiet && git diff --staged --quiet || git commit org-repos -m "$COMMIT_MESG [SKIP CI]"
            git config pull.rebase false  # merge (the default strategy)
            git push  && break  # substitute your command here
            GIT_RETRY=$((GIT_RETRY+1))
            RANDOM_WAIT_TIMER=$((1 + $RANDOM % 10))
            sleep $RANDOM_WAIT_TIMER
            git pull
            echo "RETRY COUNT: $GIT_RETRY"          
          else
            echo " ORG settings for Action Permission is not Seletected for Repositories. Please change it to selected and run the workflow"
          fi
        shell: bash
