name: Github Workflow Permission Delete
run-name: GitHUB pErm
on:
  workflow_dispatch:
    inputs:
      repo_list:
        required: true
        type: string
        description: Specify Repo Names to be DELETED. ( Make sure you DELETE the repo name from repolist.txt)
        default: "-"
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            repolist.txt
          sparse-checkout-cone-mode: false
      - name: Get noreply email address of actor
        uses: actions/github-script@v6.4.1
        id: my-script
        with:
          result-encoding: string
          script: |
            let user = await github.rest.users.getByUsername({
              username: context.actor
            });
            return `${user.data.id}+${context.actor}@users.noreply.github.com`

      - name: set git username and email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ steps.my-script.outputs.result }}"
      - name: WorkFlow Permission Adding
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
          status_check=$(curl -s -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/$org/actions/permissions | jq -r '.enabled_repositories')
          echo "$status_check"   
          if [ "$status_check" == "selected" ]; then
            IFS=',' read -r -a repo <<< "${{ inputs.repo_list }}"
            for p in "${repo[@]}"; do
            repo_id=$(curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" -H "per_page: 100"  https://api.github.com/orgs/$org/repos | jq '.[] | select(.name=="'$p'") | .id')
            curl -s -L -X DELETE  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/$org/actions/permissions/repositories/"$repo_id"
            echo "${{ inputs.action-on }} -  Operation ${{ inputs.operation }} is done for Repository $p"
            done
            IFS=',' read -r -a repo <<< "${{ inputs.repo_list }}"
            for p in "${repo[@]}"; do
            echo $p
            sed -i 's/'$p'//g' repolist.txt
            done
            cat repolist.txt
            COMMIT_MESG=$(git log -1 --pretty=format:%s | head -n 1)
            GIT_RETRY=0
            until [ "$GIT_RETRY" -ge 10 ]
            do
            git add repolist.txt
            git diff --quiet && git diff --staged --quiet || git commit repolist.txt -m "$COMMIT_MESG [SKIP CI]"
            git config pull.rebase false  # merge (the default strategy)
            git push  && break  # substitute your command here
            GIT_RETRY=$((GIT_RETRY+1))
            RANDOM_WAIT_TIMER=$((1 + $RANDOM % 10))
            sleep $RANDOM_WAIT_TIMER
            git pull
            echo "RETRY COUNT: $GIT_RETRY"
            done
          else
            echo " ORG settings for Action Permission is not Seletected for Repositories. Please change it and run the workflow"
          fi
        shell: bash
