name: Github Workflow Permission Manager New
run-name: New Permission Manager
on:
  workflow_dispatch:
    inputs:
      repos:
        required: true
        type: string
        description: Specify Repo Name or Names to be added
        default: "-"
env:
  org: bhsankbab
jobs:
  workflow-permissions:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            org-repos
          sparse-checkout-cone-mode: false
      - name: WorkFlow Permission Adding
        env:
          SUPER_SECRET: ${{ secrets.MY_TOKEN }}
          list: ${{ inputs.repo_list }}
        run: |
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions -d '{"enabled_repositories":"selected","allowed_actions":"selected"}'
            permissions=$(cat org-repos/thirdparty-sources.txt)
            content=$(echo "${permissions//$'\n'/}")
            echo $content
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/orgs/${{ env.org }}/actions/permissions/selected-actions -d '{"github_owned_allowed":true,"verified_allowed":true,"patterns_allowed":['"$content"']}'
            IFS=',' read -r -a repo <<< "${{ inputs.repos }}"
            for p in "${repo[@]}"; do
            status=`curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/${{ env.org }}/"$p" | jq -r .archived)`
            if [ "$status" = "false" ]; then
            curl -s  -L   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28"   https://api.github.com/repos/${{ env.org }}/"$p" | jq -r .id >> org-repos/ids.txt
            else
            echo " Repo $p is Archived"
            fi
            done
            IDS=$(cat org-repos/ids.txt | tr -s '\n' ',' | awk 'gsub(/,$/,x)')
            echo " $IDS "
            curl -L -X PUT  -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.MY_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/${{ env.org }}/actions/permissions/repositories -d '{"selected_repository_ids":['"$IDS"']}'
            ech " Permission is added "
        shell: bash
